# Generated by Django 4.2 on 2022-12-22 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservations", "0002_reservationjob_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IN_CART", "IN_CART"),
                    ("FAILED", "FAILED"),
                    ("PENDING", "PENDING"),
                ],
                default="PENDING",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservationjob",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "PENDING"),
                    ("COMPLETED", "COMPLETED"),
                    ("FAILED", "FAILED"),
                ],
                default="PENDING",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservationjob",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
