# Generated by Django 4.2 on 2022-12-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_reservationjob_execution_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ("selection__slot__date_time",)},
        ),
    ]
