# Generated by Django 4.2 on 2022-12-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_alter_reservation_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservationjob",
            options={"ordering": ("selection__slot__date_time",)},
        ),
        migrations.AlterField(
            model_name="reservationjob",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "PENDING"),
                    ("COMPLETED", "COMPLETED"),
                    ("FAILED", "FAILED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="PENDING",
                max_length=255,
                null=True,
            ),
        ),
    ]
