# Generated by Django 4.2 on 2022-12-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_alter_reservationjob_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationjob",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "PENDING"),
                    ("COMPLETED", "COMPLETED"),
                    ("FAILED", "FAILED"),
                    ("CANCELLED", "CANCELLED"),
                    ("APPROVED", "APPROVED"),
                ],
                default="PENDING",
                max_length=255,
                null=True,
            ),
        ),
    ]
