# Generated by Django 4.2 on 2022-12-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0007_alter_reservationjob_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IN_CART", "IN_CART"),
                    ("FAILED", "FAILED"),
                    ("PENDING", "PENDING"),
                    ("REMOVED_FROM_BASKET", "REMOVED_FROM_BASKET"),
                ],
                default="PENDING",
                max_length=255,
                null=True,
            ),
        ),
    ]
