# Generated by Django 4.2 on 2022-12-20 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("date_time", models.DateTimeField()),
                (
                    "event_target",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="SportSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "branch_name",
                    models.CharField(
                        choices=[("Tennis", "Tennis"), ("Football", "Football")],
                        max_length=255,
                    ),
                ),
                ("branch_id", models.CharField(max_length=255)),
                (
                    "complex_name",
                    models.CharField(
                        choices=[
                            ("Maltepe Sports Complex", "Maltepe Sports Complex"),
                            ("LA Sports Complex", "LA Sports Complex"),
                        ],
                        max_length=255,
                    ),
                ),
                ("complex_id", models.CharField(max_length=255)),
                (
                    "pitch_name",
                    models.CharField(
                        choices=[
                            ("Open Court", "Open Court"),
                            ("Closed Court 1", "Closed Court 1"),
                            ("Closed Court 2", "Closed Court 2"),
                            ("Closed Court 3", "Closed Court 3"),
                            ("Closed Court 4", "Closed Court 4"),
                        ],
                        max_length=255,
                    ),
                ),
                ("pitch_id", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("id",),
                "unique_together": {("branch_id", "complex_id", "pitch_id")},
            },
        ),
        migrations.CreateModel(
            name="Selection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="selections.slot",
                    ),
                ),
                (
                    "sport_selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="selections.sportselection",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
