# Generated by Django 4.2 on 2022-12-26 17:06

from dataclasses import dataclass

from django.db import migrations

BRANCH_NAME = "Tennis"
BRANCH_ID = "59b7bd71-1aab-4751-8248-7af4a7790f8c"
COMPLEX_NAME = "Maltepe Sports Complex"
COMPLEX_ID = "6989b491-bb85-414a-b470-293b190ebb44"
SULTANBEYLI_100_YIL_COMPLEX_ID = "05efe521-f4bf-4523-9632-77f1c9482791"

GENERIC_INFO = {
    "branch_name": BRANCH_NAME,
    "branch_id": BRANCH_ID,
}


@dataclass(frozen=True)
class Pitch:
    pitch_name: str
    pitch_id: str


@dataclass(frozen=True)
class Complex:
    complex_name: str
    complex_id: str


COMPLEX_ID_TO_PITCH_DATA = {
    Complex("Maltepe Sports Complex", COMPLEX_ID): [
        Pitch("Closed Court 1", "f64f68a6-7779-4f25-91d2-d7ee7ccda42e"),
        Pitch("Closed Court 2", "b3d358ee-c85b-4773-89b5-2dc14e5bcd5f"),
        Pitch("Closed Court 3", "f21006a3-26d9-480f-aa96-16b45a39e335"),
        Pitch("Closed Court 4", "88c91f40-ef33-42fc-a51f-9cf0e1912079"),
        Pitch("Open Court", "6c93b9bb-1560-4cba-926a-3632d69a05fd"),
    ],
    Complex("Sultanbeyli 100. Yil Complex", SULTANBEYLI_100_YIL_COMPLEX_ID): [
        Pitch("Closed Court 1", "9939618f-2daa-4140-aa49-78263f623ec7"),
        Pitch("Closed Court 2", "eb82b08a-0bda-4e22-9a1d-30052c3cf891"),
        Pitch("Closed Court 3", "02c31d8b-9172-4262-b8fc-1f633d0237ae"),
    ],
}

SPORT_SELECTIONS = [
    {**pitch.__dict__, **complex.__dict__, **GENERIC_INFO}
    for complex, pitches in COMPLEX_ID_TO_PITCH_DATA.items()
    for pitch in pitches
]


def add_sport_selections(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SportSelection = apps.get_model("selections", "SportSelection")

    for sport_selection in SPORT_SELECTIONS:
        SportSelection.objects.get_or_create(**sport_selection)


class Migration(migrations.Migration):

    dependencies = [
        ("selections", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_sport_selections)]
